version: "3.8"
services:

  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8080"
    depends_on:
      - order-service
      - product-service

  order-service:
    build:
      context: ./order-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ordersdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres

  product-service:
    build:
      context: ./product-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/productsdb
    depends_on:
      - mongo

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"