server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ordersdb
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info
